# Generated by Django 2.1.7 on 2019-03-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Standart'), ('P', 'Premium'), ('V', 'VIP'), ('V+', 'VIP+')], default='S', max_length=1),
        ),
    ]
