# Generated by Django 2.1.7 on 2019-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190318_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Standart'), ('P', 'Premium'), ('V', 'VIP'), ('V+', 'VIP+')], default='S', max_length=1, verbose_name='Тип цены'),
        ),
    ]
