# Generated by Django 2.1.7 on 2019-03-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190318_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=70, verbose_name='Область')),
                ('city', models.CharField(max_length=70, verbose_name='Город')),
                ('street', models.CharField(max_length=70, verbose_name='Улица')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=150, verbose_name='Название фирмы')),
                ('phone_number', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('site', models.CharField(max_length=150, verbose_name='Сайт')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Adress', verbose_name='Область')),
            ],
        ),
    ]
