# Generated by Django 2.1.7 on 2019-03-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_adress_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_construction', models.CharField(blank=True, choices=[('BB', 'Билборд'), ('BG', 'Бигборд'), ('BL', 'Бэклайт'), ('PR', 'Призматрон'), ('SC', 'Скролл')], max_length=1, verbose_name='Тип конструкции')),
                ('format', models.CharField(max_length=25)),
                ('light', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Свет')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], default='a', max_length=1, verbose_name='Сторона')),
                ('date_on', models.DateField(verbose_name='Период с: ')),
                ('date_off', models.DateField(verbose_name='Период по: ')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Adress', verbose_name='Адрес')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Price', verbose_name='Тип конструкции')),
                ('type_construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Board', verbose_name='Борд')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Adress', verbose_name='Адрес'),
        ),
    ]
