# Generated by Django 2.1.7 on 2019-03-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190319_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Ценовая категория', 'verbose_name_plural': 'Ценовые категории'},
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.Price', verbose_name='Тип конструкции'),
        ),
    ]
